<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>DfEIfcNamer</AssemblyName>
    <RootNamespace>DfEIfcNamer</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultItems>false</EnableDefaultItems>
    <Revit2024ApiPath>$(MSBuildThisFileDirectory)..\..\lib\revit2024</Revit2024ApiPath>
    <Revit2024ApiPath Condition="'$([System.Environment]::GetEnvironmentVariable('REVIT_2024_API_PATH'))' != ''">$([System.Environment]::GetEnvironmentVariable('REVIT_2024_API_PATH'))</Revit2024ApiPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="RevitAPI">
      <HintPath>$(Revit2024ApiPath)\RevitAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>$(Revit2024ApiPath)\RevitAPIUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <Page Include="UI\*.xaml" />
    <EmbeddedResource Include="Resources\*.json" />

    <None Include="Resources\ifc2x3_entity_predefinedtypes.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Resources\classification_slots.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Resources\DfE_IfcNamer_SharedParameters.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
